### ISSUE TITLE
Access to raw EEG data

### ISSUE THREAD

**Issue by gzoumpourlis** [Snapchat/NextMind#1]
Hi,

I'd like to ask, are there any plans in Snap, for releasing a code that would let users access the raw EEG data of NextMind?
Or, maybe, are there any plans to help including such a code into existing libraries, such as [BrainFlow](https://github.com/brainflow-dev/brainflow) ?

Thanks in advance for taking the time to consider this.

**Comment by VinterMute** [comment]
Great question, raw EEG data very useful for my project!)
A year ago, support answered me that they do not provide such data, but maybe something has changed now

**Comment by maxdolle** [comment]
Unfortunately, there is no plan to release code to let users access raw EEG data at Snap.

**Comment by mdolleSC** [comment]
Unfortunately, there is no plan to release code to let users access raw EEG data at Snap.

**Comment by gzoumpourlis** [comment]
Thanks for the answer @mdolleSC.
I'm closing this issue.
